# Generated by Django 4.2.9 on 2025-06-27 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResiScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('gambar', models.ImageField(upload_to='resi/')),
                ('nomor_resi', models.CharField(max_length=100)),
                ('lokasi_resi', models.CharField(max_length=100)),
            ],
        ),
    ]
